### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by marcohu** [raszi/java-progressbar#2]
I could not find any license information. I'd like to give it a try, but not knowing how the project is licensed is a showstopper. Mind clarify the license situation?

**Comment by Avec112** [comment]
May I recommend http://unlicense.org/ :+1:

**Comment by nfergu** [comment]
I made a PR for this: https://github.com/raszi/java-progressbar/pull/5

**Comment by raszi** [comment]
Closed by #9
